name: console_package
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

publish_to: none
# Add regular dependencies here.
dependencies:

  calculator:
    path: 'packages/calculator'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
